<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        'code/api/test',
        'code/api/edit',
        'code/api/taskone',
        'code/api/taskdel',
        'caiji/jieApi',
    ];

//    public function handle($request, Closure $next)
//    {
//        //如果来自 xx域名,就跳过检查
//        if ($_SERVER['SERVER_NAME'] != config('http://www.video.com/')) {
//
//            //启用
//            return parent::handle($request, $next); // TODO: Change the autogenerated stub
//        }
//        //禁用CSRF
//        return $next($request);
//    }
}
